import { useEffect, useState, type ReactNode } from 'react'
import { Bell, CheckCircle2, ClipboardList, FileText, Map, Search, Settings2, UploadCloud } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import LandMap from '../components/LandMap'
import { getAllRecords, getGISRecords, type ApprovedRecordResponse, type GISRecord } from '../services/api'
import './Dashboard.css'

export default function DashboardPage() {
  const navigate = useNavigate(); const [records, setRecords] = useState<ApprovedRecordResponse[]>([]); const [gisRecords, setGisRecords] = useState<GISRecord[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([getAllRecords(), getGISRecords()]).then(([all, gis]) => { setRecords(all.records || []); setGisRecords(gis.records || []) }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Unable to load dashboard data.')).finally(() => setLoading(false)) }, [])
  const visible = records.filter((item) => JSON.stringify(item || {}).toLowerCase().includes(query.toLowerCase())); const average = records.length ? Math.round(records.reduce((total, item) => total + (item.verification?.score || 0), 0) / records.length) : null
  return <main className="dashboard-page-view"><header className="dashboard-topbar"><div><p>BHUDRISHTI</p><h1>Land Record Intelligence</h1></div><div className="dashboard-top-actions"><div className="dashboard-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search records..." /></div><button className="icon-button" onClick={() => navigate('/notifications')} aria-label="Notifications"><Bell size={18} /></button><button className="icon-button" onClick={() => navigate('/settings')} aria-label="Settings"><Settings2 size={18} /></button><div className="profile-chip"><span>RO</span><div><b>Revenue Officer</b><small>Workspace role</small></div></div></div></header><section className="dashboard-content"><div className="dashboard-heading"><div><p className="dashboard-kicker">OVERVIEW / VERIFIED REGISTRY</p><h2>Good morning, Revenue Officer</h2><p>BhuDrishti Land Intelligence Dashboard · {new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</p></div><button className="dashboard-primary" onClick={() => navigate('/upload')}><UploadCloud size={16} /> Upload record</button></div>{error && <div className="dashboard-error">{error}</div>}{loading ? <div className="dashboard-loading">Loading dashboard...</div> : <><section className="stat-grid"><Stat icon={<FileText />} label="Total Land Records" value={records.length} /><Stat icon={<CheckCircle2 />} label="Approved Records" value={records.length} accent /><Stat icon={<ClipboardList />} label="Pending Verification" value="—" /><Stat icon={<Map />} label="Average Confidence" value={average === null ? '—' : `${average}%`} accent /></section><section className="dashboard-grid"><div className="dashboard-panel map-panel"><div className="panel-heading"><div><h3>Verified Land Records</h3><p>{gisRecords.length} parcels · application GIS view</p></div><button className="text-button" onClick={() => navigate('/gis')}>Open Full GIS Map <Map size={15} /></button></div><LandMap records={gisRecords} /></div><div className="dashboard-panel recent-panel"><div className="panel-heading"><div><h3>Recent Land Records</h3><p>{visible.length} records in registry</p></div><button className="text-button" onClick={() => navigate('/records')}>View all</button></div><div className="recent-list">{visible.slice(0, 5).map((item) => <button key={item.id || item.document_id} onClick={() => navigate(`/records/${item.id || item.document_id}`)}><span className="record-avatar">{(item.record?.owner?.name || 'U').slice(0, 1)}</span><span><b>{item.record?.owner?.name || 'Unnamed owner'}</b><small>{item.record?.land?.survey_number || 'Survey unavailable'} · {item.record?.location?.village || 'Village unavailable'}</small></span><strong>{item.verification?.score ?? '—'}%</strong></button>)}{visible.length === 0 && <div className="empty-dashboard">No approved land records yet.</div>}</div></div></section></>}</section></main>
}
function Stat({ icon, label, value, accent = false }: { icon: ReactNode; label: string; value: string | number; accent?: boolean }) { return <div className="stat-card"><span className={accent ? 'stat-icon accent' : 'stat-icon'}>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div> }
