import { useEffect, useMemo, useState } from 'react'
import { Filter, Loader2, MapPinned, Search } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import LandMap from '../components/LandMap'
import { getGISRecords, type GISRecord } from '../services/api'
import './Dashboard.css'
import './GISPage.css'

export default function GISPage() {
  const [params] = useSearchParams(); const [records, setRecords] = useState<GISRecord[]>([]); const [selectedId, setSelectedId] = useState(params.get('record') || undefined); const [query, setQuery] = useState(''); const [district, setDistrict] = useState(''); const [mandal, setMandal] = useState(''); const [village, setVillage] = useState(''); const [landType, setLandType] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { void getGISRecords().then((response) => setRecords(response.records || [])).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Unable to load GIS data.')).finally(() => setLoading(false)) }, [])
  const values = (key: keyof GISRecord) => [...new Set(records.map((record) => String(record[key] || '')).filter(Boolean))]
  const filtered = useMemo(() => records.filter((record) => JSON.stringify(record).toLowerCase().includes(query.toLowerCase()) && (!district || record.district === district) && (!mandal || record.mandal === mandal) && (!village || record.village === village) && (!landType || record.land_type === landType) && (!status || record.status === status)), [records, query, district, mandal, village, landType, status])
  function resetFilters() { setQuery(''); setDistrict(''); setMandal(''); setVillage(''); setLandType(''); setStatus('') }
  const select = (label: string, key: keyof GISRecord, value: string, setter: (next: string) => void) => <label>{label}<select value={value} onChange={(event) => setter(event.target.value)}><option value="">All</option>{values(key).map((option) => <option key={option}>{option}</option>)}</select></label>
  return <main className="gis-content"><div className="dashboard-heading"><div><p className="dashboard-kicker">VERIFIED RECORD MAP</p><h2>Application GIS View</h2><p>Verified records with deterministic demo coordinates until official cadastral GIS services are connected.</p></div><span className="gis-loaded"><MapPinned size={15} /> {records.length} parcels loaded</span></div>{error && <div className="dashboard-error">{error}</div>}{loading ? <div className="dashboard-loading"><Loader2 className="spin" /> Loading GIS data...</div> : <div className="gis-layout"><aside className="gis-filters"><div className="filter-title"><Filter size={16} /><b>Filter records</b></div><label>Search owner or survey<div className="filter-search"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search records" /></div></label>{select('District', 'district', district, setDistrict)}{select('Mandal', 'mandal', mandal, setMandal)}{select('Village', 'village', village, setVillage)}{select('Land type', 'land_type', landType, setLandType)}{select('Verification status', 'status', status, setStatus)}<button className="reset-filters" onClick={resetFilters}>Reset filters</button><p className="filter-result">{filtered.length} matching records</p></aside><section className="gis-map-area"><LandMap records={filtered} selectedId={selectedId} onSelect={setSelectedId} /></section><aside className="gis-record-list"><h3>Verified Record Map</h3><p className="map-note">Coordinates shown for demonstration.</p>{filtered.map((record) => <button className={record.record_id === selectedId ? 'gis-record selected' : 'gis-record'} key={record.record_id} onClick={() => setSelectedId(record.record_id)}><b>{record.owner || 'Unnamed owner'}</b><span>Survey {record.survey_number || '—'} · {record.village || 'Village unavailable'}</span><small>{record.land_area || 'Area unavailable'} · {record.status || 'Status unavailable'}</small></button>)}{filtered.length === 0 && <p className="filter-result">No matching GIS records.</p>}</aside></div>}</main>
}
